Changing constcalls to take target function as argument properly
Can't simulate the link on the linux testcase, current problem is:
error: linking module flags 'Code Model': IDs have conflicting values in 'units/arch/x86/entry/vdso/vclock_gettime.ll' and 'wholeprogram'

Need to check the vdso IR to understand.
Target should not be a binary, tweak the linker steps?